name: Django CI/CD Pipeline to Netlify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your Django project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Django environment
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "DEBUG=false" >> $GITHUB_ENV
          echo "ALLOWED_HOSTS=https://merry-custard-5077e6.netlify.app/" >> $GITHUB_ENV  # Replace with your actual domain or Netlify site

      - name: Run Django tests
        run: python manage.py test

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust Node version if required

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build  # Adjust command if using a different asset build process

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
